SELECT *
FROM PERSONAL;

SELECT *
FROM COMPANY;


--개인 회원 삽입
INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(1, '박미영', 'MIYOUNG', 'MIYOUNG12', '010-0000-0000'
    , '이젠', '영미', NULL, 'MI@ezen.com', '2020-01-01', '복지', '!!!!'
    ,1, SYSDATE, SYSDATE);
    
INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(2, '임찬우', 'CHANU', 'CHANU12', '010-1111-1111'
    , '이젠아', '우찬', NULL, 'CH@ezen.com', '2019-02-02', '연봉', '@@@@'
    ,2, SYSDATE+1, SYSDATE+2);

INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(3, '이승환', 'SEUNGHWAN', 'SEUNGHWAN12', '010-2222-2222'
    , '이젠아카', '환승', NULL, 'se@ezen.com', '2018-03-03', '워라밸', '####'
    , 1, SYSDATE+2, SYSDATE+3);

INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    ,PERSONAL_TEMPORARILY, PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(4, '박지훈', 'JUHOON', 'JUHOON12', '010-3333-3333'
    , '이젠데미', '영미', NULL, 'MI@ezen.com', '2017-04-04', '커리어', '$$$$'
    , 2, SYSDATE+3, SYSDATE+4);
    
INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(5, '관리자', 'admin', 'admin12', '010-9999-9999'
    , '이젠데미데미', '시스템 관리자', NULL, 'admin@ezen.com', '1999-05-05', '관리', '$$$$'
    , 10, SYSDATE, SYSDATE);    

SELECT *
FROM PERSONAL;

--기업 회원 삽입
INSERT INTO COMPANY
VALUE(COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE
    , COMPANY_HOMEPAGE, COMPANY_BUSINESS_DETAIL, COMPANY_ID, COMPANY_PASSWORD
    , COMPANY_CODE, COMPANY_LICENSE, COMPANY_LOGO, COMPANY_PRESIDENT_NAME
    , COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER, COMPANY_PREFER
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(1, '이젠', '서울시 논현', '학원', '2001-04-27', 'www.ezen.com', '수강생 배출', '일단 안씀나중에'
    , 'EZEN12', '657-58-05', '이미지들어갈거', '회사이미지', '대표이젠', '이젠인사담당자'
    , 'ezen@ezen.com', '010-2020-2020', '복지, 워라밸'
    , 5, SYSDATE-1, SYSDATE);
    
INSERT INTO COMPANY
VALUE(COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE
    , COMPANY_HOMEPAGE, COMPANY_BUSINESS_DETAIL, COMPANY_ID, COMPANY_PASSWORD
    , COMPANY_CODE, COMPANY_LICENSE, COMPANY_LOGO, COMPANY_PRESIDENT_NAME
    , COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER, COMPANY_PREFER
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(2, '이젠아', '서울시 강남', '학원2', '2003-02-27', 'www.ezena.com', '수강생 배출', '일단 안씀나중에'
    , 'EZEN23', '452-58-05', '이미지들어갈거', '회사이미지', '대표이젠아', '이젠아인사담당자'
    , 'ezen@ezen2.com', '010-2222-2222', '워라밸, 경영진'
    , 5, SYSDATE-1, SYSDATE);
    
INSERT INTO COMPANY
VALUE(COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE
    , COMPANY_HOMEPAGE, COMPANY_BUSINESS_DETAIL, COMPANY_ID, COMPANY_PASSWORD
    , COMPANY_CODE, COMPANY_LICENSE, COMPANY_LOGO, COMPANY_PRESIDENT_NAME
    , COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER, COMPANY_PREFER
    , PERMISSION, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(3, '이젠아카', '서울시 신림', '학원3', '2001-04-27', 'www.ezenaca.com', '수강생 배출', '일단 안씀나중에'
    , 'EZEN12', '447-28-08', '이미지들어갈거', '회사이미지', '대표이젠아카', '이젠아카인사담당자'
    , 'ezenaca@ezen.com', '010-1231-2312', '경력, 복지'
    , 5, SYSDATE-1, SYSDATE);
    
SELECT *
FROM COMPANY;

COMMIT;