SELECT PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD
,PERMISSION
FROM PERSONAL;

SELECT *
FROM COMPANY;


--개인 회원 삽입
INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, PERSONAL_CREATE_DATE ,PERSONAL_MODIFY_DATE
    , CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(PERSONAL_NUMBER_SEQ.NEXTVAL, '박미영', 'MIYOUNG', 'MIYOUNG12', '010-0000-0000'
    , '이젠', '영미', NULL, 'MI@ezen.com', '2020-01-01', '복지', '!!!!'
    ,1, SYSDATE, SYSDATE, SYSDATE, SYSDATE);
    
INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, PERSONAL_CREATE_DATE ,PERSONAL_MODIFY_DATE
    , CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(PERSONAL_NUMBER_SEQ.NEXTVAL, '임찬우', 'CHANU', 'CHANU12', '010-1111-1111'
    , '이젠아', '우찬', NULL, 'CH@ezen.com', '2019-02-02', '연봉', '@@@@'
    ,2, SYSDATE+1, SYSDATE+2, SYSDATE+1, SYSDATE+2);

INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, PERSONAL_CREATE_DATE ,PERSONAL_MODIFY_DATE
    , CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(PERSONAL_NUMBER_SEQ.NEXTVAL, '이승환', 'SEUNGHWAN', 'SEUNGHWAN12', '010-2222-2222'
    , '이젠아카', '환승', NULL, 'se@ezen.com', '2018-03-03', '워라밸', '####'
    , 1, SYSDATE+2, SYSDATE+3, SYSDATE+2, SYSDATE+3);

INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, PERSONAL_CREATE_DATE ,PERSONAL_MODIFY_DATE
    , CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(PERSONAL_NUMBER_SEQ.NEXTVAL, '박지훈', 'JIHOON', 'JUHOON12', '010-3333-3333'
    , '이젠데미', '영미', NULL, 'MI@ezen.com', '2017-04-04', '커리어', '$$$$'
    , 2, SYSDATE+3, SYSDATE+4, SYSDATE+3, SYSDATE+4);
    
INSERT INTO PERSONAL
VALUE(PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID
    , PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME
    , PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_KEYWORD, PERSONAL_TEMPORARILY
    , PERMISSION, PERSONAL_CREATE_DATE ,PERSONAL_MODIFY_DATE
    , CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(PERSONAL_NUMBER_SEQ.NEXTVAL, '관리자', 'admin', 'admin12', '010-9999-9999'
    , '이젠데미데미', '시스템 관리자', NULL, 'admin@ezen.com', '1999-05-05', '관리', '$$$$'
    , 10, SYSDATE, SYSDATE, SYSDATE, SYSDATE);

SELECT *
FROM PERSONAL;

--기업 회원 삽입
INSERT INTO COMPANY
VALUE(COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE
    , COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_ID, COMPANY_PASSWORD
    , COMPANY_CODE, COMPANY_LICENSE, COMPANY_LOGO, COMPANY_PRESIDENT_NAME
    , COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER, COMPANY_PREFER
    , PERMISSION,COMPANY_CREATE_DATE, COMPANY_MODIFY_DATE, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(COMPANY_NUMBER_SEQ.NEXTVAL, '이젠', '서울시 논현', '학원', '2001-04-27', 'www.ezen.com', '수강생 배출', '일단 안씀나중에'
    , 'EZEN12', '657-58-05', '이미지들어갈거', '회사이미지', '대표이젠', '이젠인사담당자'
    , 'ezen@ezen.com', '010-2020-2020', '복지, 워라밸'
    , 5, SYSDATE-1, SYSDATE, SYSDATE-1, SYSDATE);
    
INSERT INTO COMPANY
VALUE(COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE
    , COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_ID, COMPANY_PASSWORD
    , COMPANY_CODE, COMPANY_LICENSE, COMPANY_LOGO, COMPANY_PRESIDENT_NAME
    , COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER, COMPANY_PREFER
    , PERMISSION,COMPANY_CREATE_DATE, COMPANY_MODIFY_DATE, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(COMPANY_NUMBER_SEQ.NEXTVAL, '이젠아', '서울시 강남', '학원2', '2003-02-27', 'www.ezena.com', '수강생 배출', '일단 안씀나중에'
    , 'EZEN23', '452-58-05', '이미지들어갈거', '회사이미지', '대표이젠아', '이젠아인사담당자'
    , 'ezen@ezen2.com', '010-2222-2222', '워라밸, 경영진'
    , 5, SYSDATE-1, SYSDATE, SYSDATE-1, SYSDATE);
    
INSERT INTO COMPANY
VALUE(COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE
    , COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_ID, COMPANY_PASSWORD
    , COMPANY_CODE, COMPANY_LICENSE, COMPANY_LOGO, COMPANY_PRESIDENT_NAME
    , COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER, COMPANY_PREFER
    , PERMISSION,COMPANY_CREATE_DATE, COMPANY_MODIFY_DATE, CONNECTION_TIME, DISCONNECTION_TIME)
VALUES(COMPANY_NUMBER_SEQ.NEXTVAL, '이젠아카', '서울시 신림', '학원3', '2001-04-27', 'www.ezenaca.com', '수강생 배출', '일단 안씀나중에'
    , 'EZEN12', '447-28-08', '이미지들어갈거', '회사이미지', '대표이젠아카', '이젠아카인사담당자'
    , 'ezenaca@ezen.com', '010-1231-2312', '경력, 복지'
    , 5, SYSDATE-1, SYSDATE, SYSDATE-1, SYSDATE);
    
    
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                    COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                    COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
    (COMPANY_NUMBER_SEQ.NEXTVAL, 'ABC 주식회사', '서울특별시 강남구 역삼동 123-45번지', '소프트웨어 개발', '2005-03-15',
     'www.abc-company.com', '소프트웨어 및 앱 개발 및 판매', '홍길동', '이순신', 'ishin@abc-company.com', '010-1234-5678');
     
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'XYZ 주식회사', '경기도 수원시 팔달구 인계동 678-90번지', '의료기기 제조', '2010-07-20',
 'www.xyz-corp.com', '의료 기기 및 장비 제조 및 판매', '김철수', '박영희', 'yhpark@xyz-corp.com', '010-9876-5432');
 
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'EFG 주식회사', '인천광역시 남동구 구월동 234-56번지', '건설업', '2008-09-08',
 'www.efg-construction.com', '주택 건설 및 시설물 관리', '박지영', '정민우', 'mwjung@efg-construction.com', '010-5678-1234');
 
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'HIJ 주식회사', '대구광역시 수성구 만촌동 789-01번지', '식품 제조', '2015-01-10',
 'www.hij-foods.com', '다양한 식품 제조 및 유통', '이태영', '김민지', 'mjkim@hij-foods.com', '010-2345-6789');
 
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'LMN 주식회사', '부산광역시 해운대구 우동 345-67번지', '여행사', '2012-05-25',
 'www.lmn-travel.com', '여행 상품 판매 및 여행 관련 서비스 제공', '정현우', '김수진', 'sjkim@lmn-travel.com', '010-8765-4321');
 
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'OPQ 주식회사', '서울특별시 마포구 합정동 567-89번지', '음식점 운영', '2013-11-05',
 'www.opq-restaurant.com', '다국적 요리 전문 레스토랑 운영', '이성민', '박지훈', 'jhpark@opq-restaurant.com', '010-3456-7890');
 
INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'RST 주식회사', '경기도 용인시 수지구 풍덕천동 12-34번지', '화학 제품 제조', '2009-04-30',
 'www.rst-chemicals.com', '화학 제품 및 소재 제조 및 판매', '김영철', '이지영', 'jylee@rst-chemicals.com', '010-7890-1234');
 
 INSERT INTO COMPANY (COMPANY_NUMBER, COMPANY_NAME, COMPANY_ADDRESS, COMPANY_TYPE, COMPANY_ESTABLISH_DATE,
                COMPANY_HOMEPAGE, COMPANY_INTRODUCE, COMPANY_PRESIDENT_NAME,
                COMPANY_INCHARGE_NAME, COMPANY_INCHARGE_EMAIL, COMPANY_INCHARGE_PHONENUMBER)
VALUES
(COMPANY_NUMBER_SEQ.NEXTVAL, 'UVW 주식회사', '대전광역시 중구 대흥동 890-12번지', '전자 제품 제조', '2011-06-03',
 'www.uvw-electronics.com', '전자 제품 및 기기 제조 및 판매', '김태호', '이수영', 'sylee@uvw-electronics.com', '010-2345-6789');

    
SELECT *
FROM COMPANY;




INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '김영수', 'kyoungsu123', 'P@ssw0rd1', '010-1234-5678', 'ABC 주식회사', 'YoungStar', '프로파일 내용', 'youngsu@example.com', TO_DATE('2022-05-10', 'YYYY-MM-DD'), '어떤 값1', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '이지영', 'ejiyoung456', 'Secure123!', '010-9876-5432', 'XYZ 주식회사', 'SmileMaker', '프로파일 내용', 'jiyoung@example.com', TO_DATE('2022-03-15', 'YYYY-MM-DD'), '어떤 값2', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '박성민', 'parkseongmin789', 'StrongPass789', '010-5678-1234', 'EFG 주식회사', 'TechGuru', '프로파일 내용', 'seongmin@example.com', TO_DATE('2022-06-20', 'YYYY-MM-DD'), '어떤 값3', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '정지원', 'jiwonjung', 'Password@456', '010-2345-6789', 'HIJ 주식회사', 'CreativeMind', '프로파일 내용', 'jiwon@example.com', TO_DATE('2022-04-08', 'YYYY-MM-DD'), '어떤 값4', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '이민호', 'minholee', 'SecretPass789', '010-8765-4321', 'LMN 주식회사', 'Visionary', '프로파일 내용', 'minho@example.com', TO_DATE('2022-02-25', 'YYYY-MM-DD'), '어떤 값5', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '김서연', 'seoyeankim', 'S@fePass123', '010-3456-7890', 'OPQ 주식회사', 'DreamChaser', '프로파일 내용', 'seoyean@example.com', TO_DATE('2022-07-12', 'YYYY-MM-DD'), '어떤 값6', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '이준호', 'junholee', 'JH@Secure987', '010-6543-2109', 'RST 주식회사', 'DataWizard', '프로파일 내용', 'junho@example.com', TO_DATE('2022-01-05', 'YYYY-MM-DD'), '어떤 값7', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '박미라', 'mirapark123', 'MiraPass789', '010-4321-8765', 'UVW 주식회사', 'CodeNinja', '프로파일 내용', 'mira@example.com', TO_DATE('2022-08-30', 'YYYY-MM-DD'), '어떤 값8', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '김태영', 'taeyoungkim', 'TKPass456', '010-7890-1234', 'WXY 주식회사', 'TechEnthusiast', '프로파일 내용', 'taeyoung@example.com', TO_DATE('2022-09-17', 'YYYY-MM-DD'), '어떤 값9', SYSDATE, SYSDATE, 1);

INSERT INTO PERSONAL (
    PERSONAL_NUMBER, PERSONAL_NAME, PERSONAL_ID, PERSONAL_PASSWORD, PERSONAL_PHONENUMBER
    , PERSONAL_COMPANY, PERSONAL_NICKNAME, PERSONAL_PROFILE, PERSONAL_EMAIL
    , PERSONAL_HIRE_DATE, PERSONAL_TEMPORARILY, PERSONAL_CREATE_DATE, PERSONAL_MODIFY_DATE, permission
) VALUES
(PERSONAL_NUMBER_SEQ.NEXTVAL, '최수빈', 'subinchoi789', 'SB@Pass123', '010-3210-9876', 'ZAB 주식회사', 'CodeSculptor', '프로파일 내용', 'subin@example.com', TO_DATE('2022-11-11', 'YYYY-MM-DD'), '어떤 값10', SYSDATE, SYSDATE, 1);

COMMIT;


--이력서 데이터

INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '박미영', TO_DATE('1990-01-15', 'YYYY-MM-DD'), 'parkmiyoung@example.com', '010-1234-5678', '서울시 강남구'
	, 'Single', 'Female', 'No', '2008-03-01,2010-09-01,2013-02-01', '2012-12-31,2013-05-30,2017-06-30'
	, 'ABC 대학교,DEF 대학교,GHI 대학교', '전자공학,경영학,화학공학', '서울,서울,대전', 'A-,B+,A', 'Yes,Yes,Yes'
	, '2013-01-01,2015-04-01,2018-09-15', '2020-06-30,2017-08-31,2019-12-31', 'XYZ 주식회사,EFG 주식회사,HIJ 주식회사'
	, '소프트웨어 엔지니어,마케팅 매니저,품질 관리자', '서울,서울,대전', '웹 애플리케이션 개발,마케팅 전략 수립,제품 품질 관리'
    , '2015-05-20,2017-04-10,2013-06-15', 'Oracle 인증,프로젝트 관리자 인증,품질 관리자 인증', 'Oracle 교육원,PMP 인증 기관,품질 관리협회', 'Pass,Pass,Pass', 1);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '임찬우', TO_DATE('1992-08-25', 'YYYY-MM-DD'), 'limchanwoo@example.com', '010-9876-5432', '서울시 강서구'
	, 'Single', 'Male', 'No', '2010-03-01,2011-09-01,2013-01-01', '2014-12-31,2013-12-31,2016-06-30'
	, 'DEF 대학교,GHI 대학교,JKL 대학교', '경영학,화학공학,경제학', '서울,대전,부산', 'B+,A,A-', 'Yes,Yes,Yes'
	, '2015-01-01,2016-01-01,2018-03-10', '2022-07-31,2018-08-31,2019-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2017-04-10,2019-07-12,2018-08-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 2);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '이승환', TO_DATE('1988-03-10', 'YYYY-MM-DD'), 'leeseunghwan@example.com', '010-5555-5555', '서울시 강북구'
	, 'Married', 'Male', 'Yes', '2006-03-01,2007-09-01,2009-01-01', '2010-12-31,2009-12-31,2013-05-15'
	, 'GHI 대학교,JKL 대학교,MNO 대학교', '화학공학,경제학,전자공학', '대전,부산,서울', 'A,A-,A', 'Yes,Yes,Yes'
	, '2015-01-01,2016-01-01,2018-03-10', '2022-07-31,2018-08-31,2019-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2017-04-10,2019-07-12,2018-08-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 3);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '박지훈', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'hong@example.com', '010-1234-5678', '서울시 강남구'
	, 'Single', 'Male', 'No', '2008-09-01,2012-06-01', '2012-08-31,2016-05-31'
	, 'ABC 대학교,DEF 대학교','컴퓨터 공학,경영학','서울,부산','A,A-','Yes,Yes'
	, '2016-09-01,2018-07-01','2020-12-31,2022-09-30','XYZ 주식회사,ABC 주식회사','프로젝트 매니저,시스템 분석가'
    	, '서울,대전', '시스템 개발,프로젝트 계획', '2019-03-15', 'PMP 인증', 'PMP 인증 기관', 'Pass', 4);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '김영수', TO_DATE('1993-05-15', 'YYYY-MM-DD'), 'kimyoungsoo@example.com', '010-7777-8888', '서울시 송파구'
	, 'Single', 'Male', 'No', '2011-03-01,2012-09-01,2014-02-01', '2014-12-31,2014-05-30,2018-06-30'
	, 'DEF 고등학교,GHI 전문대학교,JKL 대학교', '인문계,화학공학,경제학', '서울,대전,부산', 'B+,A,A-', 'Yes,Yes,Yes'
	, '2015-01-01,2016-01-01,2018-03-10', '2022-07-31,2018-08-31,2019-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2017-04-10,2019-07-12,2018-08-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 6);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '이지영', TO_DATE('1993-05-15', 'YYYY-MM-DD'), 'leejiyeong@example.com', '010-5555-5555', '서울시 강북구', 
'Single', 'Female', 'No', '2011-03-01,2012-09-01,2014-02-01', '2014-12-31,2014-05-30,2018-06-30'
    , 'DEF 대학교,GHI 대학교,JKL 대학교', '경영학,화학공학,경제학', '서울,대전,부산', 'B+,A,A-', 'Yes,Yes,Yes', 
    '2015-01-01,2016-01-01,2018-03-10', '2022-07-31,2018-08-31,2019-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사', 
'마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구', 
    '2017-04-10,2019-07-12,2018-08-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 7);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '박성민', TO_DATE('1994-07-18', 'YYYY-MM-DD'), 'parkseongmin@example.com', '010-7777-8888', '서울시 마포구'
	, 'Single', 'Male', 'No', '2012-03-01,2013-09-01', '2016-12-31,2017-06-30'
	, 'GHI 고등학교,JKL 대학교', '인문계,경제학', '대전,서울', 'B,A,A+', 'Yes,Yes,Yes'
	, '2017-01-01,2018-01-01,2020-03-15', '2023-06-30,2019-08-31,2021-12-31', 'ABC 주식회사,DEF 주식회사,GHI 주식회사'
	, '품질 관리자,재무 분석가,데이터 분석가', '서울,서울,대전', '품질 관리,재무 분석,데이터 분석', '2019-04-20,2020-06-10,2021-07-25'
	, '품질 관리자 인증,재무 분석가 자격증,데이터 분석가 자격증', '품질 관리협회,CFA 기관,데이터 분석가 협회', 'Pass,Pass,Pass', 8);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '정지원', TO_DATE('1990-10-30', 'YYYY-MM-DD'), 'jeongjiwon@example.com', '010-3333-4444', '서울시 서초구'
    , 'Married', 'Male', 'Yes', '2008-03-01,2010-09-01,2013-02-01', 
    '2012-12-31,2013-05-30,2017-06-30', 'ABC 대학교,DEF 대학교,GHI 대학교', '전자공학,경영학,화학공학'
    , '서울,서울,대전', 'A-,B+,A', 'Yes,Yes,Yes', '2013-01-01,2015-04-01,2018-09-15', '2020-06-30,2017-08-31,2019-12-31'
    , 'XYZ 주식회사,EFG 주식회사,HIJ 주식회사', 'Oracle 인증,프로젝트 관리자 인증,품질 관리자 인증', '서울, 서울, 서울', 'Oracle 교육원,PMP 인증 기관,품질 관리협회'
    , '', '', '', '', 9);
INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '이민호', TO_DATE('1989-12-19', 'YYYY-MM-DD'), 'leeminho@example.com', '010-6666-7777', '서울시 강남구'
	, 'Married', 'Male', 'Yes', '2007-03-01,2008-09-01,2010-01-01', '2011-12-31,2010-12-31,2014-05-15'
	, 'GHI 대학교,JKL 대학교,MNO 대학교', '화학공학,경제학,전자공학', '대전,부산,서울', 'A,A-,A', 'Yes,Yes,Yes'
	, '2015-01-01,2016-01-01,2018-03-10', '2022-07-31,2018-08-31,2019-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2017-04-10,2019-07-12,2018-08-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회'
    , 'Pass,Pass,Pass', 10);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '김서연', TO_DATE('1996-02-08', 'YYYY-MM-DD'), 'kimseoyeon@example.com', '010-1234-5678', '서울시 강동구'
	, 'Single', 'Female', 'No', '2014-03-01,2015-09-01,2017-02-01', '2016-12-31,2017-05-30,2019-08-31'
	, 'ABC 대학교,DEF 대학교,GHI 대학교', '전자공학,경영학,화학공학', '서울,서울,대전', 'B+,A-,A', 'Yes,Yes,Yes'
	, '2017-01-01,2018-04-01,2020-08-15', '2023-06-30,2019-09-30,2021-12-31', 'XYZ 주식회사,EFG 주식회사,HIJ 주식회사'
	, 'Oracle 인증,프로젝트 관리자 인증,품질 관리자 인증', '서울, 대전, 서울', 'Oracle 교육원,PMP 인증 기관,품질 관리협회', '', '','', '', 11);

INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '김서연', TO_DATE('1996-02-08', 'YYYY-MM-DD'), 'kimseoyeon@example.com', '010-1234-5678', '서울시 강동구'
	, 'Single', 'Female', 'No', '2014-03-01,2015-09-01,2017-02-01', '2016-12-31,2017-05-30,2019-08-31'
	, 'ABC 대학교,DEF 대학교,GHI 대학교', '전자공학,경영학,화학공학', '서울,서울,대전', 'B+,A-,A', 'Yes,Yes,Yes'
	, '2017-01-01,2018-04-01,2020-08-15', '2023-06-30,2019-09-30,2021-12-31', 'XYZ 주식회사,EFG 주식회사,HIJ 주식회사'
	, 'Oracle 인증,프로젝트 관리자 인증,품질 관리자 인증', '서울, 대전, 서울', 'Oracle 교육원,PMP 인증 기관,품질 관리협회', '', '','', '', 11);



INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '이준호', TO_DATE('1997-09-03', 'YYYY-MM-DD'), 'leejunho@example.com', '010-9876-5432', '서울시 강서구'
	, 'Single', 'Male', 'No', '2015-03-01,2016-09-01,2019-02-01', '2018-12-31,2019-05-30,2022-07-31'
	, 'DEF 대학교,GHI 대학교,JKL 대학교', '경영학,화학공학,경제학', '서울,대전,부산', 'B,A,A-', 'Yes,Yes,Yes'
	, '2019-03-01,2020-04-01,2022-08-15', '2025-06-30,2021-08-31,2023-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2020-04-20,2021-06-10,2022-07-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 12);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '박미라', TO_DATE('1998-12-15', 'YYYY-MM-DD'), 'parkmira@example.com', '010-5555-5555', '서울시 강북구'
	, 'Married', 'Female', 'Yes', '2016-03-01,2017-09-01,2019-01-01', '2018-12-31,2019-12-31,2022-05-15'
	, 'GHI 대학교,JKL 대학교,MNO 대학교', '화학공학,경제학,전자공학', '대전,부산,서울', 'A,A-,B+', 'Yes,Yes,Yes'
	, '2022-01-01,2023-01-01,2025-03-10', '2026-07-31,2024-08-31,2026-12-31', 'ABC 주식회사,DEF 주식회사,GHI 주식회사'
	, '품질 관리자,재무 분석가,데이터 분석가', '서울,서울,대전', '품질 관리,재무 분석,데이터 분석', '2023-04-20,2024-06-10,2025-07-25'
	, '품질 관리자 인증,재무 분석가 자격증,데이터 분석가 자격증', '품질 관리협회,CFA 기관,데이터 분석가 협회', 'Pass,Pass,Pass', 13);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '김태영', TO_DATE('1995-06-20', 'YYYY-MM-DD'), 'kimtaeyoung@example.com', '010-3333-4444', '서울시 서초구'
	, 'Single', 'Male', 'No', '2013-03-01,2014-09-01,2016-01-01', '2015-12-31,2016-12-31,2019-04-30'
	, 'ABC 대학교,DEF 대학교,GHI 대학교', '전자공학,경영학,화학공학', '서울,서울,대전', 'A,B+,A-', 'Yes,Yes,Yes'
	, '2016-01-01,2017-03-01,2019-06-15', '2021-06-30,2019-08-31,2022-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2019-06-20,2020-08-10,2021-09-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 14);


INSERT INTO RESUME
VALUE(RESUME_NUMBER, RESUME_PERSONAL_NAME, RESUME_PERSONAL_BIRTHDAY
, RESUME_PERSONAL_EMAIL, RESUME_PERSONAL_PHONENUMBER
, RESUME_PERSONAL_ADDRESS, RESUME_PERSONAL_MARRY
, RESUME_PERSONAL_GENDER, RESUME_PERSONAL_MILITARY
, RESUME_EDUCATION_BEGIN_DATE, RESUME_EDUCATION_END_DATE
, RESUME_EDUCATION_NAME, RESUME_EDUCATION_MAJOR, RESUME_EDUCATION_LOCATION
, RESUME_EDUCATION_GRADE, RESUME_EDUCATION_GRADUATE, RESUME_CAREER_BEGIN_DATE
, RESUME_CAREER_END_DATE, RESUME_CAREER_NAME, RESUME_CAREER_POSITION
, RESUME_CAREER_LOCATION, RESUME_CAREER_JOB, RESUME_LICENSE_DATE, RESUME_LICENSE_NAME
, RESUME_LICENSE_INSTITUTION, RESUME_LICENSE_GRADE, PERSONAL_NUMBER)
VALUES(RESUME_NUMBER_SEQ.NEXTVAL, '최수빈', TO_DATE('1993-09-05', 'YYYY-MM-DD'), 'choisubin@example.com', '010-9999-1111', '서울시 송파구'
	, 'Single', 'Female', 'No', '2011-03-01,2012-09-01,2014-02-01', '2014-12-31,2014-05-30,2018-06-30'
	, 'DEF 대학교,GHI 대학교,JKL 대학교', '경영학,화학공학,경제학', '서울,대전,부산', 'B+,A,A-', 'Yes,Yes,Yes'
	, '2015-01-01,2016-01-01,2018-03-10', '2022-07-31,2018-08-31,2019-12-31', 'EFG 주식회사,MNO 주식회사,STU 주식회사'
	, '마케팅 매니저,금융 애널리스트,화학 연구원', '서울,서울,대구', '마케팅 전략 수립,금융 분석 및 모델링,화학 실험 및 연구'
	, '2017-04-10,2019-07-12,2018-08-25', 'PMP 인증,금융 애널리스트 인증,화학 연구원 인증', 'PMP 인증 기관,금융 애널리스트 협회,화학 협회', 'Pass,Pass,Pass', 15);


UPDATE RESUME
SET RESUME_EDUCATION_NAME = '송곡 고등학교,서일전문대학'
WHERE PERSONAL_NUMBER = 2;

UPDATE RESUME
SET RESUME_EDUCATION_NAME = '아파트 고등학교'
WHERE PERSONAL_NUMBER = 11;

UPDATE RESUME
SET RESUME_EDUCATION_NAME = '그린 고등학교, ABC전문대학'
WHERE PERSONAL_NUMBER = 14;

UPDATE RESUME
SET RESUME_EDUCATION_NAME = 'DEF 대학교,GHI 전문대학,JKL 대학교'
WHERE PERSONAL_NUMBER = 6;

--리뷰 데이터
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '좋았어요', '급여와 복지가 좋았고 근무 환경도 만족스러웠습니다.', 5, 5, 4, 4, 5, 4.6, SYSDATE, SYSDATE, 1, 1);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '매우 만족스러웠어요', '이 회사에서 일하게 되어 행복했습니다. 경영진 역시 훌륭했어요.', 4, 5, 5, 4, 5, 4.6, SYSDATE, SYSDATE, 2, 1);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '그냥 그랬어요', '복지는 괜찮았지만 급여가 높지는 않아서 아쉬웠습니다.', 3, 4, 3, 3, 3, 3.2, SYSDATE, SYSDATE, 3, 1);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '별로에요', '근무 환경이 좋지 않았고 경영진의 의사 결정이 이해하기 어려웠어요.', 2, 2, 2, 2, 2, 2.0, SYSDATE, SYSDATE, 4, 1);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '만족스러웠어요', '워라밸이 좋았고 팀장님도 친절하셨습니다.', 4, 4, 5, 4, 4, 4.2, SYSDATE, SYSDATE, 5, 2);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '매우 훌륭했어요', '급여와 복지, 근무 환경, 경영진, 워라밸 모두 만족스러웠습니다.', 5, 5, 5, 5, 5, 5.0, SYSDATE, SYSDATE, 6, 2);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '그럭저럭', '일은 열심히 했지만 급여가 아쉬웠습니다.', 3, 3, 3, 3, 3, 3.0, SYSDATE, SYSDATE, 7, 3);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '최악이에요', '여기서 일하는 동안 힘들었습니다. 급여도 낮고 복지도 부족합니다.', 1, 1, 2, 1, 2, 1.4, SYSDATE, SYSDATE, 8, 3);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '별로에요', '복지는 좋았지만 급여가 낮아서 불만족스러웠습니다.', 2, 4, 3, 3, 3, 2.8, SYSDATE, SYSDATE, 9, 3);
INSERT INTO REVIEW (
    REVIEW_NUMBER, REVIEW_TITLE, REVIEW_CONTENT,
    REVIEW_SALARY, REVIEW_WELFARE, REVIEW_ENVIRONMENT, REVIEW_BOSS, REVIEW_BALANCE,
    REVIEW_AVERAGE, REVIEW_CREATE_DATE, REVIEW_MODIFY_DATE,
    PERSONAL_NUMBER, COMPANY_NUMBER
) VALUES
(REVIEW_NUMBER_SEQ.NEXTVAL, '그냥 그랬어요', '회사 분위기는 좋았지만 급여와 복지가 아쉬웠습니다.', 3, 3, 4, 3, 3, 3.2, SYSDATE, SYSDATE, 10, 3);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 박미영은 이렇게 자랐다.', '나 박미영은 이러한 이유때문에 지원하게 되었습니다.'
    ,'나 박미영의 장단점은 이런것이다.', '나 박미영의 목표는 이러하다.', 1);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 임찬우는 이렇게 자랐다.', '나 임찬우는 이러한 이유때문에 지원하게 되었습니다.'
    , '나 임찬우의 장단점은 이런것이다.', '나 임찬우의 목표는 이러하다.', 2);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 이승환은 이렇게 자랐다.', '나 이승환은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 이승환의 장단점은 이런것이다.', '나 이승환의 목표는 이러하다.', 3);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 박지훈은 이렇게 자랐다.', '나 박지훈은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 박지훈의 장단점은 이런것이다.', '나 박지훈의 목표는 이러하다.', 4);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 김영수는 이렇게 자랐다.', '나 김영수는 이러한 이유때문에 지원하게 되었습니다.'
    , '나 김영수의 장단점은 이런것이다.', '나 김영수의 목표는 이러하다.', 6);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 이지영은 이렇게 자랐다.', '나 이지영은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 이지영의 장단점은 이런것이다.', '나 이지영의 목표는 이러하다.', 7);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 박성민은 이렇게 자랐다.', '나 박성민은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 박성민의 장단점은 이런것이다.', '나 박성민의 목표는 이러하다.', 8);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 정지원은 이렇게 자랐다.', '나 정지원은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 정지원의 장단점은 이런것이다.', '나 정지원의 목표는 이러하다.', 9);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 이민호는 이렇게 자랐다.', '나 이민호는 이러한 이유때문에 지원하게 되었습니다.'
    , '나 이민호의 장단점은 이런것이다.', '나 이민호의 목표는 이러하다.', 10);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 김서연은 이렇게 자랐다.', '나 김서연은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 김서연의 장단점은 이런것이다.', '나 김서연의 목표는 이러하다.', 11);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 이준호는 이렇게 자랐다.', '나 이준호는 이러한 이유때문에 지원하게 되었습니다.'
    , '나 이준호의 장단점은 이런것이다.', '나 이준호의 목표는 이러하다.', 12);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 박미라는 이렇게 자랐다.', '나 박미라는 이러한 이유때문에 지원하게 되었습니다.'
    , '나 박미라의 장단점은 이런것이다.', '나 박미라의 목표는 이러하다.', 13);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 김태영은 이렇게 자랐다.', '나 김태영은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 김태영의 장단점은 이런것이다.', '나 김태영의 목표는 이러하다.', 14);

INSERT INTO LETTER
VALUE(LETTER_NUMBER, LETTER_HISTORY, LETTER_MOTIVATION
    , LETTER_CHARACTER, LETTER_GOAL, PERSONAL_NUMBER)
VALUES(LETTER_NUMBER_SEQ.NEXTVAL, '나 최수빈은 이렇게 자랐다.', '나 최수빈은 이러한 이유때문에 지원하게 되었습니다.'
    , '나 최수빈의 장단점은 이런것이다.', '나 최수빈의 목표는 이러하다.', 15);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '영미', '안녕하세요', '잘 부탁드려요', SYSDATE, SYSDATE, 1, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '우찬', '반가워요', '안녕하세요?', SYSDATE, SYSDATE, 2, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '환승', '설레네요', '글은 처음 남겨요', SYSDATE, SYSDATE, 3, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '영미', '자기소개하세요', '저는 박씨입니다', SYSDATE, SYSDATE, 4, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '시스템 관리자', '저도 글을 남겨도 될까요?', '하하', SYSDATE, SYSDATE, 5, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, 'YoungStar', '전 김영수에요', '반가워요', SYSDATE, SYSDATE, 6, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, 'SmileMaker', '미소가 예쁜여자', '잘 부탁해요', SYSDATE, SYSDATE, 7, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, 'TechGuru', '한강 가고싶어요', '요즘 날씨가 너무 좋아서 한강가고 싶네요', SYSDATE, SYSDATE, 8, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, 'CreativeMind', '어디든 떠나고 싶어요', '훌쩍', SYSDATE, SYSDATE, 9, 0, 0);

INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_WRITER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE
    , BOARD_MODIFY_DATE, PERSONAL_NUMBER, BOARD_LIKE_COUNT, BOARD_VIEWS)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, 'Visionary', '배우?', '아니죠', SYSDATE, SYSDATE, 10, 0, 0);

COMMIT;